AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'Rakefile'
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

