name: 'RSpec'

on: [push]

jobs:
  tests:
    name: 'RSpec'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Ruby gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: 'RSpec'
        run: bundle exec rspec --format progress
