name: RSpec

on: [push]

jobs:
  tests:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: RSpec
        run: bundle exec rspec --format progress
