name: 'RuboCop'

on: [push]

jobs:
  lint:
    name: 'RuboCop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install RuboCop
        run: |
          gem install bundler --no-document
          gem install rubocop -v 0.90 --no-document
      - name: 'RuboCop'
        run: rubocop
